Topic/content
Pelagicore/template-library pull request #1
Opened 2017-06-26 13:04 UTC by GordanM

2017-06-26 14:06 UTC, rpannek requested changes

2017-06-26 14:06 UTC, rpannek commented on CMakeLists.txt
> +set(PROJECT_VERSION ${PROJECT_MAJOR_VERSION}.${PROJECT_MINOR_VERSION}.${PROJECT_PATCH_LEVEL})
Wouldn't it be nicer to set the version in the project() call like the documentation suggests? https://cmake.org/cmake/help/v3.0/command/project.html

2017-06-26 14:06 UTC, rpannek commented on include/templatepublicclass.h
> +    std::shared_ptr<TemplatePrivateClass> templatePrivateClass;
Wouldn't it make more sense to call the variable `templatePrivateInstance` or `templatePrivateProperty`?

2017-06-26 14:06 UTC, rpannek commented on include/templatepublicclass.h
> +    TemplatePublicClass();
Perhaps you could add a `helloWorld()` method which would return a "hello world" string or something which we then could call from the service which uses this library?

2017-06-26 14:27 UTC, GordanM commented
@rpannek thanks for the review. I've addressed your comments and a commit has been changed.

2017-06-26 14:58 UTC, rpannek approved these changes

2017-06-27 11:05 UTC, GordanM commented
@breakreturn and @rpannek I have added the .pc.in file as suggested. Could you please check it?

2017-06-27 11:07 UTC, rpannek approved these changes
Looking good!

2017-06-27 11:38 UTC, merged