Add coverage target
Pelagicore/template-library pull request #6
Opened 2018-03-07 15:27 UTC by BassemMohsen

* Update CMakeLists to configure the build to generate unit testing coverage
results
* Add build target for coverage results

2018-03-07 15:38 UTC, GordanM requested changes
Good stuff, some minor comment and the signed-off tag is missing.

2018-03-07 15:38 UTC, GordanM commented on CMakeLists.txt
> +if ( CMAKE_BUILD_TYPE STREQUAL "Coverage" OR CMAKE_BUILD_TYPE STREQUAL "Debug" )
Sometimes you leave a space between the `( CMAKE` and sometimes you don't `(CMAKE_CXX_FLAGS)`. Could you please change the commit so these are consistent?

2018-03-08 08:23 UTC, kursatkobya commented on README.md
> +This project uses tools such as lcov, gcov, genhtml to collect and generate code
could you remove words "such as"

2018-03-08 08:27 UTC, kursatkobya requested changes
just a minor comment

2018-03-08 09:44 UTC, kursatkobya approved these changes
Looks good to me.

2018-03-08 11:59 UTC, merged

2018-03-08 12:08 UTC, GordanM commented
@BassemMohsen usually you shouldn't merge a commit that has a red `X` but since you've fixed all the issues I presume it's fine this time.